import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SolanaProvider } from "@/components/SolanaProvider";
import { Inter, Jersey_15 } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});

const jersey = Jersey_15({
  variable: "--font-jersey",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen antialiased ${inter.variable} ${jersey.variable}`}
      >
        <SolanaProvider>
          <Header />
          {children}
          <Footer />
        </SolanaProvider>
      </body>
    </html>
  );
}
